name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-action:
    name: GitHub Actions Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Test Local Action
        id: test-action

        uses: ./

      - name: Test action with plugins
        id: test-action-with-plugins
        uses: ./
        with:
          wash-version: "wash-v1.0.0-beta.10"
          plugins: "ghcr.io/cosmonic-labs/plugins/openapi2mcp:0.3.0"
